MODEL_IMPORT_MAPS = {
    'ols' : {"import_name": 'linear_model', "model_name": '.LinearRegression', 
        "supervised": 1, "regression": 1},
    'ridge': {"import_name": 'linear_model', "model_name": '.Ridge', 
        "supervised": 1, "regression": 1},
    'lasso': {"import_name": 'linear_model', "model_name": '.Lasso', 
        "supervised": 1, "regression": 1},
    'elastic_net': {"import_name": 'linear_model', "model_name": '.ElasticNet', 
        "supervised": 1, "regression": 1},
    'log_reg': {"import_name": 'linear_model', "model_name": '.LogisticRegression', 
        "supervised": 1, "regression": 1},
    'kernel_ridge': {"import_name": 'kernel_ridge', "model_name": '.KernelRidge', 
        "supervised": 1, "regression": 1},
    'svc' : {"import_name": 'svm', "model_name": '.SVC', 
        "supervised": 1, "regression": 0},
    'svr' : {"import_name": 'svm', "model_name": '.SVR', 
        "supervised": 1, "regression": 1},
    'GaussianNB' : {"import_name": 'naive_bayes', "model_name": '.GaussianNB', 
        "supervised": 1, "regression": 0},
    'BernoulliNB' : {"import_name": 'naive_bayes', "model_name": '.BernoulliNB', 
        "supervised": 1, "regression": 0},
    'MultinomialNB' : {"import_name": 'naive_bayes', "model_name": '.MultinomialNB', 
        "supervised": 1, "regression": 0},
    'dec_treeC' : {"import_name": 'tree', "model_name": '.DecisionTreeClassifier', 
        "supervised": 1, "regression": 0},
    'dec_treeR' : {"import_name": 'tree', "model_name": '.DecisionTreeRegressor', 
        "supervised": 1, "regression": 1},
    'rfc' : {"import_name": 'ensemble', "model_name": '.RandomForestClassifier', 
        "supervised": 1, "regression": 0},
    'rfr' : {"import_name": 'ensemble', "model_name": '.RandomForestRegressor', 
        "supervised": 1, "regression": 1},
    'MLPC' : {"import_name": 'neural_network', "model_name": '.MLPClassifier', 
        "supervised": 1, "regression": 0},
    'MLPR' : {"import_name": 'neural_network', "model_name": '.MLPRegressor', 
        "supervised": 1, "regression": 1},
    'KMeans' : {"import_name": 'cluster', "model_name": '.KMeans', 
        "supervised": 0, "regression": 0},
    'MiniBatchKMeans' : {"import_name": 'cluster', "model_name": '.MiniBatchKMeans', 
        "supervised": 0, "regression": 0},
    'AffinityPropagation' : {"import_name": 'cluster', "model_name": '.AffinityPropagation', 
        "supervised": 0, "regression": 0},
    'MeanShift' : {"import_name": 'cluster', "model_name": '.MeanShift', 
        "supervised": 0, "regression": 0},
    'Spectral_Clustering' : {"import_name": 'cluster', "model_name": '.SpectralClustering', 
        "supervised": 0, "regression": 0},
    'Hierarchical_Clustering' : {"import_name": 'cluster', "model_name": '.AgglomerativeClustering', 
        "supervised": 0, "regression": 0},
    'DBSCAN' : {"import_name": 'cluster', "model_name": '.DBSCAN', 
        "supervised": 0, "regression": 0},
    'Birch' : {"import_name": 'cluster', "model_name": '.Birch', 
        "supervised": 0, "regression": 0},
    'GaussianMixture' : {"import_name": 'mixture', "model_name": '.GaussianMixture', 
        "supervised": 0, "regression": 0},
    'BayesianGaussianMixture' : {"import_name": 'mixture', "model_name": '.BayesianGaussianMixture', 
        "supervised": 0, "regression": 0}
}
S3_BUCKET_PATH = 's3/path/to/encrypted/dataset'
DOCKER_VOLUME_PATH = '/home/docker_vol/'
